export { CommandLine } from "./internal/execute/tsc.js";
export type { CommandLineResult, CommandLineTesting, ExitStatus, System } from "./internal/execute/tsc/compile.js";
export type { CompilerHost } from "./internal/compiler/host.js";
export type { Program, ProgramLike, ProgramOptions } from "./internal/compiler/program.js";
export {
  TstsSourceProviderContractVersion,
  argumentPassingFactKey,
  associatedTypeFactKey,
  attributeFactKey,
  canonicalIdentityFactKey,
  constGenericFactKey,
  createSourceSemanticsExtension,
  defaultValueFactKey,
  defineExtensionFactKey,
  fieldFactKey,
  flowStateFactKey,
  functionPointerFactKey,
  pointerFactKey,
  pointerOperationFactKey,
  rawPointerFactKey,
  rawPointerOperationFactKey,
  providerTypeFamilyFactKey,
  providerVirtualDeclarationFactKey,
  sourcePrimitive,
  sourceSemanticsExtensionId,
  sourcePrimitiveFactKey,
  sourceMarkerFactKey,
  structFactKey,
} from "./extensions/index.js";
export type {
  ArgumentPassingFact,
  ArgumentPassingMode,
  AssociatedTypeFact,
  AttributeFact,
  CompilerExtension,
  CompilerExtensionIdentity,
  CheckedSourceProgram,
  ConstGenericFact,
  DefaultValueFact,
  ExtensionCanonicalIdentity,
  ExtensionCanonicalIdentityKind,
  ExtensionDependencySpec,
  ExtensionDiagnostic,
  ExtensionDiagnosticCategory,
  ExtensionDiagnosticRange,
  ExtensionDiagnosticSourceSpan,
  ExtensionDiagnosticWriter,
  ExtensionEvidence,
  ExtensionFactEntry,
  ExtensionFactKey,
  ExtensionFactKeyOptions,
  ExtensionFactReader,
  ExtensionFactResolution,
  ExtensionFactResolverCallback,
  ExtensionFactResolverContext,
  ExtensionFactSubject,
  ExtensionFactWriteResult,
  ExtensionHostOptions,
  ExtensionImportKind,
  ExtensionInitializeContext,
  FieldFact,
  FlowStateFact,
  FunctionPointerFact,
  PointerFact,
  PointerOperationFact,
  RawPointerFact,
  RawPointerOperationFact,
  ProviderDeclarationIdentity,
  ProviderDeclarationKind,
  ProviderDeclarationMaterialization,
  ProviderDeclarationModel,
  ProviderDeclarationRequest,
  ProviderCompleteExportRequest,
  ProviderExportDeclaration,
  ProviderExportKind,
  ProviderHeritageDeclaration,
  ProviderIdentity,
  ProviderImportDeclaration,
  ProviderImportRequestKind,
  ProviderImportSlice,
  ProviderImportSliceKind,
  ProviderMemberDeclaration,
  ProviderMemberKey,
  ProviderModuleContext,
  ProviderModuleResolution,
  ProviderModuleResolveResult,
  ProviderOwnership,
  ProviderParameterDeclaration,
  ProviderPropertyName,
  ProviderRequestedExport,
  ProviderResolutionMode,
  ProviderResolvedModule,
  ProviderSignatureDeclaration,
  ProviderTypeExpression,
  ProviderTypeFamilyDeclaration,
  ProviderTypeFamilyFact,
  ProviderTypeFamilyVariantFact,
  ProviderTypeParameterDeclaration,
  ProviderVirtualDeclarationDocument,
  ProviderVirtualDeclarationFact,
  ProviderVirtualModuleArtifact,
  ProviderWellKnownSymbolName,
  RequiredProviderModuleSpec,
  ReadonlySourceFactResolver,
  SourceAnalysisContext,
  SourceAnalysisFactAccess,
  SourceAnalysisFactResolver,
  SourceCallMarkerDeclaration,
  SourceCallMarkerKind,
  SourceDeclarationProvider,
  SourceDeclarationMaterializationMode,
  SourceFileQueries,
  SourcePointerMutability,
  SourceMarkerFact,
  SourceProgramQueries,
  SourcePrimitiveDeclaration,
  SourcePrimitiveFact,
  SourcePrimitiveKind,
  SourceSemanticsExportDeclaration,
  SourceSemanticsExtensionOptions,
  SourceSemanticsModule,
  SourceSemanticsModuleCapability,
  SourceSemanticsModuleIdentity,
  SourceTypeMarkerDeclaration,
  SourceTypeMarkerKind,
  StructFact,
} from "./extensions/index.js";
export { ParseBuildCommandLine, ParseCommandLine } from "./internal/tsoptions/commandlineparser.js";
export type { ParsedBuildCommandLine } from "./internal/tsoptions/parsedbuildcommandline.js";
export type { ParsedCommandLine } from "./internal/tsoptions/parsedcommandline.js";
export { barebonesLibContent, formatDiagnostics, transpile, transpileDeclaration, transpileModule } from "./services/transpile.js";
export type { TranspileCompilerOptions, TranspileCompilerOptionValue, TranspileOptions, TranspileOutput } from "./services/transpile.js";
export type {
  ResolvedSourceCallInfo,
  ResolvedSourceElementAccessInfo,
  ResolvedSourceIterationInfo,
  ResolvedSourceGeneratorInfo,
  ResolvedSourceObjectLiteralElementInfo,
  ResolvedSourceObjectLiteralElementKind,
  ResolvedSourcePropertyAccessInfo,
  ResolvedSourceResourceManagementInfo,
  ResolvedSourceStorageInfo,
  ResolvedSourceWellKnownSymbolInfo,
  ResolvedSourceYieldInfo,
  TypeCheckerQueries,
} from "./services/type-checker.js";
export { createCompilerHost, createInMemoryFileSystem, getBundledLibraryClosure, getBundledLibraryPath, withBundledLibraries } from "./services/embedding-host.js";
export type { BundledLibrarySource, CompilerFileSystem, CompilerHostOptions, CompilerTraceCallback, InMemoryFileSystemOptions } from "./services/embedding-host.js";
export type { AstAuthoredRange, AstModifierKind, AstReader, AstVariableDeclarationKind } from "./services/ast-reader.js";
export { createCompilerSession, createCompilerSessionFromFiles, createCompilerSessionFromProgram } from "./services/compiler-session.js";
export type { CompilerDiagnosticKind, CompilerSession, CompilerSessionOptions, InMemoryCompilerSessionOptions } from "./services/compiler-session.js";
export type {
  TypeIndexInfo,
  TypePropertyInfo,
  TypeSignatureParameterInfo,
  TypeSignatureThisParameterInfo,
  TypeShapeQueries,
  TypeTupleElementInfo,
} from "./services/type-shape.js";
export type { Node, SourceFile } from "./internal/ast/ast.js";
export type { Symbol } from "./internal/ast/symbol.js";
export type { ContextFlags, Signature, Type } from "./internal/checker/types.js";
